In [5]:
import pandas as pd

In [6]:
df = pd.read_excel(r'C:\Users\Notebook\Downloads\Etudiants.xlsx')

In [7]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [8]:
df.head()

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0

In [9]:
df.head(10)

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [10]:
df.tail()

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [11]:
df.tail(8)

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [12]:
df.shape

(20, 9)

In [13]:
type(df.shape)

tuple

In [14]:
df.shape[0]

20

In [15]:
df.shape[1]

9

In [16]:
df.iloc[0: 1]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0

In [17]:
df.iloc[0: 4]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0

In [18]:
# Fetch from 4 to 6
df.iloc[3: 6]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0

In [19]:
# depicts from the 7 to the 9 row
df.iloc[6:9]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0

In [20]:
df.iloc[0].values

array(['CD000001', 'BOUZIDI AMINE', '09/03/2000', 'FES', 14.29,
       'sciences mathématiques a', 14.07, 'SMI', 3.0], dtype=object)

In [21]:
type(df.iloc[0].values)

numpy.ndarray

In [22]:
df.iloc[0].values[7]

'SMI'

In [23]:
df.iloc[0].values[-2]

'SMI'

In [24]:
df['Date de Naissance']

0     09/03/2000
1      2003-12-8
2      1994-6-28
3     25/11/2002
4     19/10/2003
5       8/8/1999
6      2004-1-23
7     01/01/2001
8     28/02/2002
9      1998-5-16
10     29/2/1992
11    08/10/1995
12           NaN
13    25/11/2002
14     2003-12-8
15    28/02/2002
16     2004-1-23
17     1994-6-28
18      8/8/1999
19    01/01/2001
Name: Date de Naissance, dtype: object

In [25]:
type(df['Date de Naissance'])

pandas.core.series.Series

In [26]:
df['Date de Naissance'].values

array(['09/03/2000', '2003-12-8', '1994-6-28', '25/11/2002', '19/10/2003',
       '8/8/1999', '2004-1-23', '01/01/2001', '28/02/2002', '1998-5-16',
       '29/2/1992', '08/10/1995', nan, '25/11/2002', '2003-12-8',
       '28/02/2002', '2004-1-23', '1994-6-28', '8/8/1999', '01/01/2001'],
      dtype=object)

In [27]:
# Depicts the values asscociated to the column named 'Date de Naissance'
type(df['Date de Naissance'].values)

numpy.ndarray

In [28]:
# Depicts the birthday of the fifth student in the dataframe
df['Date de Naissance'].values[4]

'19/10/2003'

In [29]:
df.columns

Index(['CIN', 'Nom et Prenom ', 'Date de Naissance', 'Lieu de Naissance',
       'Note Bac', 'Option Bac', 'Note Licence', 'Option Licence',
       'Nombre Années'],
      dtype='object')

In [30]:
df.columns[0]

'CIN'

In [32]:
df['Nom et Prenom '].values # Is the same as : df[df.columns[1]].values

array(['BOUZIDI AMINE', 'ALAMI ALAE', 'ZANOUU ABDERAHIMME',
       'BENSLIMANE ILHAME', 'AMMI KARIM', 'SAIQ MOHAMMED', 'OUATIK JALAL',
       'ZAIM MERIAM', 'CHIBI HIBA', 'DMINI SAAD', 'AOUADI HAMZA',
       'SAMI ILIASS', 'ALAOUI ANASS', 'BENSLIMANE ILHAME', 'ALAMI ALAE',
       'CHIBI HIBA', 'OUATIK JALAL', 'ZANOUU ABDERAHIMME',
       'SAIQ MOHAMMED', 'ZAIM MERIAM'], dtype=object)

In [33]:
df.columns[1]

'Nom et Prenom '

In [34]:
df[df.columns[1]].values

array(['BOUZIDI AMINE', 'ALAMI ALAE', 'ZANOUU ABDERAHIMME',
       'BENSLIMANE ILHAME', 'AMMI KARIM', 'SAIQ MOHAMMED', 'OUATIK JALAL',
       'ZAIM MERIAM', 'CHIBI HIBA', 'DMINI SAAD', 'AOUADI HAMZA',
       'SAMI ILIASS', 'ALAOUI ANASS', 'BENSLIMANE ILHAME', 'ALAMI ALAE',
       'CHIBI HIBA', 'OUATIK JALAL', 'ZANOUU ABDERAHIMME',
       'SAIQ MOHAMMED', 'ZAIM MERIAM'], dtype=object)

In [35]:
df[df.columns[-3]].values

array([14.07, 15.31, 12.52, 13.46, 15.94, 16.09, 10.  , 14.87, 15.23,
       11.68,   nan,   nan,   nan, 13.46, 15.31, 15.23, 10.  , 12.52,
       16.09, 14.87])

In [36]:
# depicts the two columns CIN and Date de Naissance
df[['CIN', 'Date de Naissance']]

         CIN Date de Naissance
0   CD000001        09/03/2000
1   CD000002         2003-12-8
2   CD000003         1994-6-28
3   CD000004        25/11/2002
4   CD000005        19/10/2003
5   CD000006          8/8/1999
6   CD000007         2004-1-23
7   CD000008        01/01/2001
8   CD000009        28/02/2002
9   CD000010         1998-5-16
10  CD000011         29/2/1992
11  CD000012        08/10/1995
12  CD000013               NaN
13  CD000004        25/11/2002
14  CD000002         2003-12-8
15  CD000009        28/02/2002
16  CD000007         2004-1-23
17  CD000003         1994-6-28
18  CD000006          8/8/1999
19  CD000008        01/01/2001

In [37]:
# depicts the three columns CIN, Date de Naissance and Note Bac
df[['CIN', 'Date de Naissance', 'Note Bac']]

         CIN Date de Naissance  Note Bac
0   CD000001        09/03/2000     14.29
1   CD000002         2003-12-8     10.52
2   CD000003         1994-6-28     11.01
3   CD000004        25/11/2002     18.17
4   CD000005        19/10/2003     13.85
5   CD000006          8/8/1999     17.00
6   CD000007         2004-1-23     10.68
7   CD000008        01/01/2001     12.96
8   CD000009        28/02/2002     15.73
9   CD000010         1998-5-16     16.44
10  CD000011         29/2/1992       NaN
11  CD000012        08/10/1995     16.01
12  CD000013               NaN       NaN
13  CD000004        25/11/2002     18.17
14  CD000002         2003-12-8     10.52
15  CD000009        28/02/2002     15.73
16  CD000007         2004-1-23     10.68
17  CD000003         1994-6-28     11.01
18  CD000006          8/8/1999     17.00
19  CD000008        01/01/2001     12.96

In [38]:
df[['CIN', 'Date de Naissance', 'Note Bac']].values

array([['CD000001', '09/03/2000', 14.29],
       ['CD000002', '2003-12-8', 10.52],
       ['CD000003', '1994-6-28', 11.01],
       ['CD000004', '25/11/2002', 18.17],
       ['CD000005', '19/10/2003', 13.85],
       ['CD000006', '8/8/1999', 17.0],
       ['CD000007', '2004-1-23', 10.68],
       ['CD000008', '01/01/2001', 12.96],
       ['CD000009', '28/02/2002', 15.73],
       ['CD000010', '1998-5-16', 16.44],
       ['CD000011', '29/2/1992', nan],
       ['CD000012', '08/10/1995', 16.01],
       ['CD000013', nan, nan],
       ['CD000004', '25/11/2002', 18.17],
       ['CD000002', '2003-12-8', 10.52],
       ['CD000009', '28/02/2002', 15.73],
       ['CD000007', '2004-1-23', 10.68],
       ['CD000003', '1994-6-28', 11.01],
       ['CD000006', '8/8/1999', 17.0],
       ['CD000008', '01/01/2001', 12.96]], dtype=object)

In [39]:
df[['CIN', 'Date de Naissance', 'Note Bac']].values[2]

array(['CD000003', '1994-6-28', 11.01], dtype=object)

In [40]:
df[['CIN', 'Date de Naissance', 'Note Bac']].values[2][1]

'1994-6-28'

In [41]:
# depicts the two columns CIN and Date de Naissance for the first row

df[['CIN', 'Date de Naissance']].iloc[0:1]

        CIN Date de Naissance
0  CD000001        09/03/2000

In [42]:
# depicts the two columns CIN and Date de Naissance for row 6, 7 and 8

df[['CIN', 'Date de Naissance']].iloc[5:8]

        CIN Date de Naissance
5  CD000006          8/8/1999
6  CD000007         2004-1-23
7  CD000008        01/01/2001

In [43]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [44]:
df["Nombre Années"] > 5

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18    False
19    False
Name: Nombre Années, dtype: bool

In [45]:
# Apply filters : Students with licence obtained in more than 5 years
df[df["Nombre Années"] > 5]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0

In [46]:
df[df["Nombre Années"] >= 4]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0

In [47]:
df[df["Note Licence"] >= 15]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0

In [48]:
df[df["Note Licence"] >= 15]['Nom et Prenom '].values

array(['ALAMI ALAE', 'AMMI KARIM', 'SAIQ MOHAMMED', 'CHIBI HIBA',
       'ALAMI ALAE', 'CHIBI HIBA', 'SAIQ MOHAMMED'], dtype=object)

In [49]:
# retrieves the rows in which the value of the column 'Lieu de Naissance' is FEZ
df[df['Lieu de Naissance'] == 'FES']

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0

In [50]:
# retrieves the rows in which the value of the column 'Lieu de Naissance' is 'FEZ' or 'RABAT'
df[(df['Lieu de Naissance'] == 'FES') | (df['Lieu de Naissance'] == 'RABAT')]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [51]:
# retrieves the rows in which the value of the column 'Lieu de Naissance' is 'FEZ' or 'RABAT'
df[df['Lieu de Naissance'].isin(['FES', 'RABAT'])]

# The same thing as : df[(df['Lieu de Naissance'] == 'FES') | (df['Lieu de Naissance'] == 'RABAT')]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [52]:
# retrieves the rows in which the value of the column 'Lieu de Naissance' is 'FEZ' and Option Bac is 'SCIENCES MATHÉMATIQUES B'
df[(df['Lieu de Naissance'] == 'FES') & (df['Option Bac'] == 'SCIENCES MATHÉMATIQUES B')]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.0,SMC,4.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.0,SMC,4.0

In [53]:
# depicts statistics of numerical columns
df.describe()

        Note Bac  Note Licence  Nombre Années
count  18.000000     17.000000      18.000000
mean   14.040556     13.920588       4.055556
std     2.819504      1.979831       1.109967
min    10.520000     10.000000       3.000000
25%    11.010000     12.520000       3.000000
50%    14.070000     14.870000       4.000000
75%    16.332500     15.310000       5.000000
max    18.170000     16.090000       6.000000

In [54]:
# depicts global information about each column of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CIN                20 non-null     object
 1   Nom et Prenom      20 non-null     object
 2   Date de Naissance  19 non-null     object
 3   Lieu de Naissance  19 non-null     object
 4   Note Bac           18 non-null     float64
 5   Option Bac         18 non-null     object
 6   Note Licence       17 non-null     float64
 7   Option Licence     18 non-null     object
 8   Nombre Années      18 non-null     float64
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

In [55]:
# depicts duplicated rows
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14     True
15     True
16     True
17     True
18     True
19     True
dtype: bool

In [56]:
df[df.duplicated()]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [57]:
# Remove duplicates
df.drop_duplicates()

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
14,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
15,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
16,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
17,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
18,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
19,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0

In [60]:
#df = df.drop_duplicates() 
# or
df.drop_duplicates(inplace= True)

In [61]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df['Note Bac'].isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12     True
Name: Note Bac, dtype: bool

In [63]:
# depicts rows in which the column named 'Note Bac' is NaN

df[df['Note Bac'].isna()]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
# depicts rows in which the column named 'Note Bac' is NaN or 'Option Licence' is NaN
df[df['Note Bac'].isna() | df['Option Licence'].isna()]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
# depicts rows in which the column named 'Note Bac' is NaN and 'Option Licence' is NaN
df[df['Note Bac'].isna() & df['Option Licence'].isna()]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
# depicts rows in which one or many columns are NaN
df[df.isna().any(axis=1)]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
df.isna().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
12     True
dtype: bool

In [68]:
# Depicts rows with a null value
df[df.isna().any(axis=1)]

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
# Depicts columns with a null value

df.isna().any(axis=0)

CIN                  False
Nom et Prenom        False
Date de Naissance     True
Lieu de Naissance     True
Note Bac              True
Option Bac            True
Note Licence          True
Option Licence        True
Nombre Années         True
dtype: bool

In [70]:
# retrieve the number of missing values in each column of the DataFrame.
df.isnull().sum()

CIN                  0
Nom et Prenom        0
Date de Naissance    1
Lieu de Naissance    1
Note Bac             2
Option Bac           2
Note Licence         3
Option Licence       2
Nombre Années        2
dtype: int64

In [71]:
# retrieve the number of missing values in each row of the DataFrame.
df.isnull().sum(axis = 1)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    4
11    2
12    7
dtype: int64

In [72]:
# replace NaN values with 'VIDE'
df.fillna('AUCUNE')

# replace NaN values with 'VIDE' make it permanent
# df = df.fillna('AUCUNE') or df.fillna('AUCUNE', inplace = True)

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.0,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.0,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,AUCUNE,AUCUNE,AUCUNE,Sciences Mathématiques et Informatique,AUCUNE
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,AUCUNE,AUCUNE,4.0
12,CD000013,ALAOUI ANASS,AUCUNE,AUCUNE,AUCUNE,AUCUNE,AUCUNE,AUCUNE,AUCUNE

In [73]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0
10,CD000011,AOUADI HAMZA,29/2/1992,FES,NaN,NaN,NaN,Sciences Mathématiques et Informatique,NaN
11,CD000012,SAMI ILIASS,08/10/1995,NADOR,16.01,SCIENCES PHYSIQUES,NaN,NaN,4.0
12,CD000013,ALAOUI ANASS,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
# removing rows that contain null values
df.dropna(inplace= True)
##or
#df = df.dropna()

In [75]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [81]:
nom = []
prenom = []
for i in (df['Nom et Prenom '].values):
    nom.append(i.split(' ')[0])
    prenom.append(i.split(' ')[1])
print(nom)
print(prenom)

['BOUZIDI', 'ALAMI', 'ZANOUU', 'BENSLIMANE', 'AMMI', 'SAIQ', 'OUATIK', 'ZAIM', 'CHIBI', 'DMINI']
['AMINE', 'ALAE', 'ABDERAHIMME', 'ILHAME', 'KARIM', 'MOHAMMED', 'JALAL', 'MERIAM', 'HIBA', 'SAAD']

In [83]:
df.insert(1, 'Nom', nom)

In [85]:
df.insert(2, 'Prenom', prenom)

In [86]:
df

,CIN,Nom,Prenom,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI,AMINE,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI,ALAE,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU,ABDERAHIMME,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE,ILHAME,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI,KARIM,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ,MOHAMMED,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK,JALAL,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM,MERIAM,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI,HIBA,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI,SAAD,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [89]:
df.drop('Nom', axis = 1, inplace = True)

In [91]:
df.drop('Prenom', axis = 1, inplace = True)

In [92]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [93]:
df[["Nom", "Prenom"]] = df["Nom et Prenom "].str.split(' ', n=1, expand=True)

In [94]:
df

,CIN,Nom et Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années,Nom,Prenom
0,CD000001,BOUZIDI AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0,BOUZIDI,AMINE
1,CD000002,ALAMI ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0,ALAMI,ALAE
2,CD000003,ZANOUU ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0,ZANOUU,ABDERAHIMME
3,CD000004,BENSLIMANE ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0,BENSLIMANE,ILHAME
4,CD000005,AMMI KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0,AMMI,KARIM
5,CD000006,SAIQ MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0,SAIQ,MOHAMMED
6,CD000007,OUATIK JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0,OUATIK,JALAL
7,CD000008,ZAIM MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0,ZAIM,MERIAM
8,CD000009,CHIBI HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0,CHIBI,HIBA
9,CD000010,DMINI SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0,DMINI,SAAD

In [95]:
# Drop the column named "Nom et Prenom"
df = df.drop("Nom et Prenom ", axis=1)

In [96]:
df

,CIN,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années,Nom,Prenom
0,CD000001,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0,BOUZIDI,AMINE
1,CD000002,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0,ALAMI,ALAE
2,CD000003,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0,ZANOUU,ABDERAHIMME
3,CD000004,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0,BENSLIMANE,ILHAME
4,CD000005,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0,AMMI,KARIM
5,CD000006,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0,SAIQ,MOHAMMED
6,CD000007,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0,OUATIK,JALAL
7,CD000008,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0,ZAIM,MERIAM
8,CD000009,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0,CHIBI,HIBA
9,CD000010,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0,DMINI,SAAD

In [98]:
"BENLAHBIB MOHAMMED AMINE".split(' ', maxsplit = 1) # equivalent to n= 1 in pandas

['BENLAHBIB', 'MOHAMMED AMINE']

In [99]:
df.columns

Index(['CIN', 'Date de Naissance', 'Lieu de Naissance', 'Note Bac',
       'Option Bac', 'Note Licence', 'Option Licence', 'Nombre Années', 'Nom',
       'Prenom'],
      dtype='object')

In [103]:
# Change columns order
df[[df.columns[0], df.columns[-2], df.columns[-1], df.columns[1], df.columns[2], df.columns[3], df.columns[4], df.columns[5], df.columns[6], df.columns[7]]]

,CIN,Nom,Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI,AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI,ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU,ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE,ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI,KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ,MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK,JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM,MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI,HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI,SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [105]:
df[['CIN', 'Nom']]

        CIN         Nom
0  CD000001     BOUZIDI
1  CD000002       ALAMI
2  CD000003      ZANOUU
3  CD000004  BENSLIMANE
4  CD000005        AMMI
5  CD000006        SAIQ
6  CD000007      OUATIK
7  CD000008        ZAIM
8  CD000009       CHIBI
9  CD000010       DMINI

In [106]:
# Change columns order
df = df[[df.columns[0], df.columns[-2], df.columns[-1], df.columns[1], df.columns[2], df.columns[3], df.columns[4], df.columns[5], df.columns[6], df.columns[7]]]

In [107]:
df

,CIN,Nom,Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI,AMINE,09/03/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI,ALAE,2003-12-8,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU,ABDERAHIMME,1994-6-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE,ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI,KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ,MOHAMMED,8/8/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK,JALAL,2004-1-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM,MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI,HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI,SAAD,1998-5-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [110]:
# Convert the "Date de Naissance" column to datetime format
df["Date de Naissance"] = pd.to_datetime(df["Date de Naissance"], format='mixed')

In [111]:
df

,CIN,Nom,Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI,AMINE,2000-09-03,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI,ALAE,2003-12-08,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU,ABDERAHIMME,1994-06-28,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE,ILHAME,2002-11-25,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI,KARIM,2003-10-19,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ,MOHAMMED,1999-08-08,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK,JALAL,2004-01-23,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM,MERIAM,2001-01-01,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI,HIBA,2002-02-28,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI,SAAD,1998-05-16,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [112]:
# Convert date column to day/month/year format
df["Date de Naissance"] = df["Date de Naissance"].dt.strftime('%d/%m/%Y')

In [113]:
df

,CIN,Nom,Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI,AMINE,03/09/2000,FES,14.29,sciences mathématiques a,14.07,SMI,3.0
1,CD000002,ALAMI,ALAE,08/12/2003,RABAT,10.52,sciences mathématiques b,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU,ABDERAHIMME,28/06/1994,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE,ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI,KARIM,19/10/2003,DAKHLA,13.85,sciences de la vie et de la terre,15.94,SVI,3.0
5,CD000006,SAIQ,MOHAMMED,08/08/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK,JALAL,23/01/2004,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM,MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI,HIBA,28/02/2002,MEKNES,15.73,sciences physiques,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI,SAAD,16/05/1998,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [114]:
df['Option Bac'].unique()

array(['sciences mathématiques a', 'sciences mathématiques b',
       ' SCIENCES PHYSIQUES', 'sciences de la vie et de la terre',
       'SCIENCES MATHÉMATIQUES B', 'SCIENCES DE LA VIE ET DE LA TERRE',
       ' sciences physiques', 'SCIENCES MATHÉMATIQUES A'], dtype=object)

In [116]:
df['Option Bac'] = df['Option Bac'].str.upper()

In [117]:
df['Option Bac'].unique()

array(['SCIENCES MATHÉMATIQUES A', 'SCIENCES MATHÉMATIQUES B',
       ' SCIENCES PHYSIQUES', 'SCIENCES DE LA VIE ET DE LA TERRE'],
      dtype=object)

In [118]:
df

,CIN,Nom,Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI,AMINE,03/09/2000,FES,14.29,SCIENCES MATHÉMATIQUES A,14.07,SMI,3.0
1,CD000002,ALAMI,ALAE,08/12/2003,RABAT,10.52,SCIENCES MATHÉMATIQUES B,15.31,Sciences Mathématiques et Applications,3.0
2,CD000003,ZANOUU,ABDERAHIMME,28/06/1994,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE,ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,Sciences de la Matière Chimie,6.0
4,CD000005,AMMI,KARIM,19/10/2003,DAKHLA,13.85,SCIENCES DE LA VIE ET DE LA TERRE,15.94,SVI,3.0
5,CD000006,SAIQ,MOHAMMED,08/08/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK,JALAL,23/01/2004,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM,MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,Sciences de la Vie,3.0
8,CD000009,CHIBI,HIBA,28/02/2002,MEKNES,15.73,SCIENCES PHYSIQUES,15.23,Sciences de la Matière Physique,3.0
9,CD000010,DMINI,SAAD,16/05/1998,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,Sciences Mathématiques et Informatique,5.0

In [119]:
df['Option Licence'].unique()

array(['SMI', 'Sciences Mathématiques et Applications', 'SMP',
       'Sciences de la Matière Chimie', 'SVI', 'SMA', 'SMC',
       'Sciences de la Vie', 'Sciences de la Matière Physique',
       'Sciences Mathématiques et Informatique'], dtype=object)

In [121]:
mapping = {
    'Sciences Mathématiques et Informatique': 'SMI',
    'Sciences Mathématiques et Applications': 'SMA',
    'Sciences de la Vie': 'SVI',
    'Sciences de la Matière Physique': 'SMP',
    'Sciences de la Matière Chimie': 'SMC'
}

df["Option Licence"] = df["Option Licence"].replace(mapping) ### or df["Option Licence"].replace(mapping, inplace=True)

In [122]:
df['Option Licence'].unique()

array(['SMI', 'SMA', 'SMP', 'SMC', 'SVI'], dtype=object)

In [123]:
df

,CIN,Nom,Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
0,CD000001,BOUZIDI,AMINE,03/09/2000,FES,14.29,SCIENCES MATHÉMATIQUES A,14.07,SMI,3.0
1,CD000002,ALAMI,ALAE,08/12/2003,RABAT,10.52,SCIENCES MATHÉMATIQUES B,15.31,SMA,3.0
2,CD000003,ZANOUU,ABDERAHIMME,28/06/1994,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE,ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,SMC,6.0
4,CD000005,AMMI,KARIM,19/10/2003,DAKHLA,13.85,SCIENCES DE LA VIE ET DE LA TERRE,15.94,SVI,3.0
5,CD000006,SAIQ,MOHAMMED,08/08/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK,JALAL,23/01/2004,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM,MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,SVI,3.0
8,CD000009,CHIBI,HIBA,28/02/2002,MEKNES,15.73,SCIENCES PHYSIQUES,15.23,SMP,3.0
9,CD000010,DMINI,SAAD,16/05/1998,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,SMI,5.0

In [125]:
df.to_excel(r'C:\Users\Notebook\Downloads\Etudiants_Cleaned.xlsx', index = False)

In [126]:
df.to_csv(r'C:\Users\Notebook\Downloads\Etudiants_Cleaned.csv', index = False)

In [128]:
# Groupby single column
df.groupby('Option Bac')['CIN'].count()

Option Bac
 SCIENCES PHYSIQUES                  3
SCIENCES DE LA VIE ET DE LA TERRE    2
SCIENCES MATHÉMATIQUES A             2
SCIENCES MATHÉMATIQUES B             3
Name: CIN, dtype: int64

In [131]:
# Groupby multiple columns
df.groupby(['Lieu de Naissance', 'Option Bac'])['Note Bac'].count()

Lieu de Naissance  Option Bac
DAKHLA             SCIENCES DE LA VIE ET DE LA TERRE    1
FES                 SCIENCES PHYSIQUES                  1
                   SCIENCES MATHÉMATIQUES A             2
                   SCIENCES MATHÉMATIQUES B             1
MEKNES              SCIENCES PHYSIQUES                  1
                   SCIENCES MATHÉMATIQUES B             1
RABAT              SCIENCES DE LA VIE ET DE LA TERRE    1
                   SCIENCES MATHÉMATIQUES B             1
TANGER              SCIENCES PHYSIQUES                  1
Name: Note Bac, dtype: int64

In [132]:
# Groupby multiple aggregations
df.groupby('Lieu de Naissance')['Note Bac'].aggregate(['min','max'])

                     min    max
Lieu de Naissance
DAKHLA             13.85  13.85
FES                10.68  16.44
MEKNES             15.73  17.00
RABAT              10.52  12.96
TANGER             18.17  18.17

In [133]:
# Groupby & multiple aggregations on different columns
df.groupby('Lieu de Naissance').aggregate({'Option Bac':'count','Note Bac':['min','max']})

                  Option Bac Note Bac
                       count      min    max
Lieu de Naissance
DAKHLA                     1    13.85  13.85
FES                        4    10.68  16.44
MEKNES                     2    15.73  17.00
RABAT                      2    10.52  12.96
TANGER                     1    18.17  18.17

In [134]:
# Drop a row
df.drop(index = df.index[0])

,CIN,Nom,Prenom,Date de Naissance,Lieu de Naissance,Note Bac,Option Bac,Note Licence,Option Licence,Nombre Années
1,CD000002,ALAMI,ALAE,08/12/2003,RABAT,10.52,SCIENCES MATHÉMATIQUES B,15.31,SMA,3.0
2,CD000003,ZANOUU,ABDERAHIMME,28/06/1994,FES,11.01,SCIENCES PHYSIQUES,12.52,SMP,5.0
3,CD000004,BENSLIMANE,ILHAME,25/11/2002,TANGER,18.17,SCIENCES PHYSIQUES,13.46,SMC,6.0
4,CD000005,AMMI,KARIM,19/10/2003,DAKHLA,13.85,SCIENCES DE LA VIE ET DE LA TERRE,15.94,SVI,3.0
5,CD000006,SAIQ,MOHAMMED,08/08/1999,MEKNES,17.00,SCIENCES MATHÉMATIQUES B,16.09,SMA,5.0
6,CD000007,OUATIK,JALAL,23/01/2004,FES,10.68,SCIENCES MATHÉMATIQUES B,10.00,SMC,4.0
7,CD000008,ZAIM,MERIAM,01/01/2001,RABAT,12.96,SCIENCES DE LA VIE ET DE LA TERRE,14.87,SVI,3.0
8,CD000009,CHIBI,HIBA,28/02/2002,MEKNES,15.73,SCIENCES PHYSIQUES,15.23,SMP,3.0
9,CD000010,DMINI,SAAD,16/05/1998,FES,16.44,SCIENCES MATHÉMATIQUES A,11.68,SMI,5.0